POST https://playingwithnode.onrender.com/videos
content-type: application/json

{
  "title": "video node",
  "description": "Esse é o primeiro video",
  "duration": 180
}

###

GET https://playingwithnode.onrender.com/videos


###

PUT https://playingwithnode.onrender.com/videos/012b43aa-6271-459d-b531-efa89ebb21a8
content-type: application/json

{
  "title": "video 02",
  "description": "Esse é o primeiro video",
  "duration": 180
}


###

DELETE https://playingwithnode.onrender.com/videos/012b43aa-6271-459d-b531-efa89ebb21a8